 services:
  - type: web
    name: crop-prediction-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
